name: Build with Maven

on: [pull_request, push]

jobs:
    test:
     runs-on: ubuntu-latest
     steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build with Maven
        run: mvn package -DskipTests  # Optionally add -DskipTests to skip tests

      - name: Build and test with Maven
        run: mvn -B package